spring:
  datasource:
    password: gRHWJt88R5
    url: jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6462407?useSSL=false
    username: sql6462407
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
